### ISSUE TITLE
update, delete, create methods in server project not implemented

### ISSUE THREAD

**Issue by ghost** [XamarinUniversity/ENT410#2]
hi, I attended xamarin university and went through all the modules. Fantastic stuff and highly recommend other team members go through the training.

with regards to this demo - I deployed to azure webapp and updated sql connection string.

updated the app to connect to the url endpoint.

sync action in app always returns error.

after looking into it further.
the serverapi project - none of the sql create, update, delete methods are implemented.
public async virtual Task<int> InsertAsync(T item)
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// Updates an existing entry in the database
        /// </summary>
        /// <param name="item"></param>
        public async virtual Task UpdateAsync(T item)
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// Deletes an entry in the database
        /// </summary>
        /// <param name="item"></param>
        public async virtual Task DeleteAsync(T item)
        {
            throw new NotImplementedException();
        }
appreciate your guidance.

**Comment by glennstephens** [comment]
What you are looking at there is the base class which is really the abstract model of how an item is synchronised on the server. To see a real implementation take a look at [DatabaseCustomerDataSync.cs](https://github.com/XamarinUniversity/ENT410/blob/master/Demos/CustomerSync/CustomerSync.Server/DatabaseCustomerDataSync.cs) which shows a sub-class working against an Entity Framework Core system to perform the CRUD operations. 

This then links against an implementation like [CustomersController.cs](https://github.com/XamarinUniversity/ENT410/blob/master/Demos/CustomerSync/ServerSyncApi/Controllers/CustomersController.cs#L20) that maps the DTO to the synchronisation implementation being used.
