### ISSUE TITLE
sql DB - script

### ISSUE THREAD

**Issue by ghost** [XamarinUniversity/ENT410#3]
is there a tsql script of the DB? or is there another way to get the DB deployed for this demo?

I created an empty DB - ran the project - no tables get created.

**Comment by glennstephens** [comment]
The example projects used Entity Framework Core using Code First, so it is expected that you would setup the database on the server using the appropriate command Line tools. You can find more information on using the command line tools [here](https://ef.readthedocs.io/en/staging/miscellaneous/cli/powershell.html)
